---
title: "Untitled"
author: "Put your name here"
date: "3/30/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(tidymodels)
library(DALEX)
library(DALEXtra)
```

```{r}
data("lending_club") # dataset

lending_mod <- read_rds("../rf_final.rds")
```


```{r}
lending_club  %>% 
  select(where(is.numeric)) %>% 
  names()
```


```{r}
lending_club  %>% 
  select(where(is.numeric)) %>% 
  pivot_longer(cols = everything(),
               names_to = "variable", 
               values_to = "value") %>% 
  group_by(variable) %>% 
  summarize(min_val = min(value),
            max_val = max(value),
            med_val = median(value))

```

```{r}
lending_club  %>% 
  select(!where(is.numeric)) %>% 
  pivot_longer(cols = everything(),
               names_to = "variable", 
               values_to = "value") %>% 
  group_by(variable) %>% 
  summarize(distinct_val = n_distinct(value))
```

```{r}
states <- 
  lending_club %>% 
  select(addr_state) %>% 
  distinct(addr_state) %>% 
  arrange(addr_state) %>% 
  pull(addr_state)
```

```{r}
paste(names(lending_club), 
       " = input$", 
       names(lending_club),
       sep = "",
       collapse = ", ")
```


